### ISSUE TITLE
Hand tracker not tracking

### ISSUE THREAD

**Issue by MarkusEich** [FORTH-ModelBasedTracker/HandTracker#13]
I made the tracker run with a Kinect sensor. I can see the image with a hand in the middle. The problem is that the hand is not tracking. When I move the hand into the vicinity, the hand model does not move. Any ideas? Maybe some params to adjust?

Cheers,

Markus

**Comment by padeler** [comment]
Did you press 's'? Does the script work with th .oni file ? Give some more details on the output of the tracker.

**Comment by MarkusEich** [comment]
Yes the tracker is working with the oni file.  What is done with the s key? Can check tomorrow. (hope s is not the start button :-) 

Am 26. November 2015 19:47:12 GMT+10:00, schrieb Panteleris Paschalis notifications@github.com:

**Comment by padeler** [comment]
's' starts/stops the tracking. Check the comments inside the script.

**Comment by MarkusEich** [comment]
Will check tomorrow. If it works please remove this comment. This is embarrassing :-) 

Am 26. November 2015 22:03:30 GMT+10:00, schrieb Panteleris Paschalis notifications@github.com:
