### ISSUE TITLE
Live capture error

### ISSUE THREAD

**Issue by Humster1991** [FORTH-ModelBasedTracker/HandTracker#15]
Hello, I can not run the tracker in live capture

I set the path to the empty string (oniPath = ''). But OpenNI error is occured.

My system is windows10, CUDA 7.5 and Kinect v2.

Could you tell me how to solve it ?

**Comment by nkyriazis** [comment]
Please be more specific about the error you're getting.

Regardless, have you installed OpenNI SDK and driver, according to the instructions? Is the sensor connected? Can you confirm that other OpenNI-based applications (e.g. NiViewer) work?

**Comment by Humster1991** [comment]
I saw #8. And then, I could run the tracker by installing OpenNI driver.
Thank you very much.
