### ISSUE TITLE
HandTracker live capture

### ISSUE THREAD

**Issue by basti35** [FORTH-ModelBasedTracker/HandTracker#19]
I was able to run the offline detection, by setting oniPath to a previous registration.

Trying to have a live capture with a Aus Xtion live pro, I obtain this error:

```
$ ./runtest.sh
[2016-01-14 15:36:37.041002] [0x000007f819cf4474] [error]   Xn function Failed: A timeout has occurred when waiting for new data!
```

Trying to get more information I edited the runme.sh, opening a interactive python shell. I changed the last line into:
`python -i src/SingleHandTracking.py`

Not always, but more than 90%, of times this is what I got when grabbing from the device:

```
>>> acq.grab()
[2016-01-14 15:37:20.962590] [0x000007f00be23674] [error]   Xn function Failed: A timeout has occurred when waiting for new data!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: /home/padeler/work/mbv/release_libs/src/mbv/Acquisition/OpenNIGrabber/OpenNIGrabber.cpp(171): Throw in function void MBV::Acquisition::OpenNIGrabber::xnCheckReturnCode(int)
Dynamic exception type: boost::exception_detail::clone_impl<MBV::Core::Exception>
[MBV::Core::Message*] = OpenNI error. Function Failed
```

The Xtion is working and with NiViewer I can have a proper live video. I used this to record new oni file to try your tracker.
The problem occurs only when grabbing the image with grab method. Do you have any hints?

**Comment by padeler** [comment]
Does NiViewer work with full resolution (VGA) and registered streams?.
By default NiViewer starts with qvga res, while the Hand Tracker script opens the device in vga-registered mode.

It looks like a USB bus issue, this can happen if more tha one high speed device are sharing the same bus (i.e another camera).

If that is the case, try a different usb port.
