### ISSUE TITLE
runme.sh shows video repetetively of the demonstrator, doesnt show the output from my sensor

### ISSUE THREAD

**Issue by shomedas** [FORTH-ModelBasedTracker/HandTracker#21]
setup :ubuntu14.04,64 bit, cuda-7.5, nvidiagtx960, carmine 1.09

when i run runme.sh i see 
![output_runme](https://cloud.githubusercontent.com/assets/14357750/13028141/23722fea-d28c-11e5-86f4-a4011c9937be.png)

the message on the terminal is:

$./runme.sh 
MBV_LIBS Environment variable should point to the MBV libraries folder.
MBV_LIBS /home/himalaya/shome/forth_hand_tracking/MBV_PythonAPI_Linux_1.1
Setting LD_LIBRARY_PATH and PYTHONPATH
Running the Single Hand Tracker script...
Creating Renderer...
**[2016-02-13 19:58:10.302617] [0x000007f366a72974] [warning] Read options from environment : unrecognised option 'libs'
[2016-02-13 19:58:10.302728] [0x000007f366a72974] [warning] Read options from environment : unrecognised option 'libs'**
*\*  Warning! Material file '/home/himalaya/shome/forth_hand_tracking/HandTracker-master/media/sphere.mtl' not found!
Warning! Material '' not defined in material file.
  Warning! Material file '/home/himalaya/shome/forth_hand_tracking/HandTracker-master/media/cylinder.mtl' not found!**
Warning! Material '' not defined in material file.
Variances:  [10.0, 10.0, 10.0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
Low Bounds:  [-2000.0, -2000.0, -2000.0, -1.0, -1.0, -1.0, -1.0, 0.0, 1.2999999523162842, 0.0, 0.0, 0.0, 2.5, 0.0, 0.0, 0.0, 1.2999999523162842, 0.0, 0.0, 0.0, 1.2999999523162842, 0.0, 0.0, 0.0, 1.2999999523162842, 0.0, 0.0]
High Bounds:  [2000.0, 2000.0, 2000.0, 1.0, 1.0, 1.0, 1.0, 1.5700000524520874, 1.840000033378601, 1.5700000524520874, 1.5700000524520874, 1.0, 3.140000104904175, 1.5700000524520874, 1.5700000524520874, 1.5700000524520874, 1.840000033378601, 1.5700000524520874, 1.5700000524520874, 1.5700000524520874, 1.840000033378601, 1.5700000524520874, 1.5700000524520874, 1.5700000524520874, 1.840000033378601, 1.5700000524520874, 1.5700000524520874]
Randomization Indices:  [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
Starting Grabber...
Entering main Loop.
init done 
opengl support available 

why is it not showing my sensor output?

**Comment by padeler** [comment]
Please have a look at this [comment](https://github.com/FORTH-ModelBasedTracker/HandTracker/blob/master/src/SingleHandTracking.py#L89). You'll find that it suffices to set <tt>oniPath</tt> ([next line](https://github.com/FORTH-ModelBasedTracker/HandTracker/blob/master/src/SingleHandTracking.py#L90)) to the empty string.
