### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by WangZixuan** [FORTH-ModelBasedTracker/HandTracker#25]
Hello, thanks for your work. I am working with Kinect to do some research.

I received the following import error. 

> MBV_LIBS Environment variable should point to the MBV libraries folder.
> MBV_LIBS D:\MBV_PythonAPI_Win_1.1
> Setting PATH and PYTHONPATH
> "Running the Single Hand Tracker script..."
> Traceback (most recent call last):
>   File "src\SingleHandTracking.py", line 10, in <module>
>     import PyMBVAcquisition as Acquisition
> ImportError: DLL load failed: The specified module could not be found.

If I commented on line 10, I would get this:

>  File "src\SingleHandTracking.py", line 17, in <module>
>     import PyHandTracker as HT

I only had problems with these two DLLs. That is to say, if I had commented these two lines, the 'import' part worked. What happened?
Thank you for your kind attention.

**Comment by nkyriazis** [comment]
Have you installed Kinect SDK 2?

**Comment by WangZixuan** [comment]
Yes, from https://www.microsoft.com/en-us/download/details.aspx?id=44561

**Comment by nkyriazis** [comment]
I trust that you've followed the install instructions.

I suggest using the Dependency Walker (http://www.dependencywalker.com/) to figure out which dlls are not found and lead to the import problem you're having.

**Comment by WangZixuan** [comment]
Thank you for your time. I fixed the dependency problems.
But I had the same problem as issue 23 now, which was 

> RuntimeError: 'output': reserved word

As you explained on that issue, It may be with  OpenGL and NVidia driver versions, so are there some recommendations on these driver versions?
Thank you.

**Comment by nkyriazis** [comment]
If you find that the error was due to our instructions please let us know so that we fix it.

The driver I'm using on Windows 8 is 353.90.

Please know that the "output" error will be fixed in a next release.

**Comment by kheito** [comment]
Can you share on how you solve the line 10 problem? I'm having that problem right now. Thanks in advance

**Comment by padeler** [comment]
This is a dependency issue (missing camera drivers/libs). Make sure all the dependencies are properly installed.

**Comment by kheito** [comment]
Thanks for the quick response, very much appreciated. We are using KinectV2 as our camera. Btw, do I still need to install OpenNI even though I am using KinectV2 as our device??

![error_line10](https://user-images.githubusercontent.com/26784621/27382989-9314e036-56bb-11e7-8cd0-106f67d2a05e.png)

**Comment by padeler** [comment]
Yes, the lib was compiled with support for both openni and kinect so you need to have both installed.

**Comment by kheito** [comment]
It's working now. Thanks!

**Comment by GosseMol** [comment]
I had to add C:\Program Files\OpenNI\Bin64 to my PATH to fix this
