### ISSUE TITLE
Source of the MVB libraries

### ISSUE THREAD

**Issue by severin-lemaignan** [FORTH-ModelBasedTracker/HandTracker#3]
The README [mentions](https://github.com/FORTH-ModelBasedTracker/HandTracker/blob/master/README.md#L6) that the MVB librairies are open-source, but the source is not available in this repository. It would be nice to add a link to the source, so that we can compile ourselves the project (which may solve issue #2).

**Comment by nkyriazis** [comment]
The MBV libraries are in binary form and can be used freely for academic and non-profit purposes.

The python script which implements 3D Hand Tracking, by using the MBV libraries, is open.

We will notify if anything changes. Until then, we'll consider this issue closed.
