### ISSUE TITLE
C++ Interface

### ISSUE THREAD

**Issue by justinhart** [FORTH-ModelBasedTracker/HandTracker#33]
I was poking around in the DLLs and it seems like there's a bunch of C++ code under the hood. Is there any chance that you'll provide a C++ library for HandTracker? We have a significant codebase for a project written in Visual C++, and this would simplify matters quite a bit for us!

**Comment by nkyriazis** [comment]
Actually, all code is in C++, except for the python script that makes use of the bindings. Eventually, we will provide C++ libraries, but this remains unspecified.

For the moment I suggest you setup some minimal python bindings for the part of your code that needs interfacing with the hand tracking library, and do this interfacing in python, where there's a plethora of other useful tools, too. We use boost::python, which I recommend.
