### ISSUE TITLE
Core.ParamVector()?

### ISSUE THREAD

**Issue by Freshy123** [FORTH-ModelBasedTracker/HandTracker#37]
Good Afternoon,

I am working with a group at Rochester Institute of Technology, I have been working with the python code for the your hand tracking libraries located in HandTracker-master > src > SingleHandTracking.py . I have been tasked with retrieving the tracking data from the python code. I noticed that your variable Core.ParamVector() is used to keep track of the current hand position. My question is what are the dependencies Core.ParamVector() takes and how should I read the dependencies so that I may determine the exact distances.

Very Respectfully,

Dominic Paul Curcione
dpc9190@rit.edu
Rochester Institute of Technology

**Comment by nkyriazis** [comment]
I'm not sure what the issue is but I think that #16 might be of help.
