### ISSUE TITLE
Running Singlehandtracking.py with two Kinects

### ISSUE THREAD

**Issue by Freshy123** [FORTH-ModelBasedTracker/HandTracker#39]
Good Afternoon,

This is the Imaging Science group from R.I.T. once again we have been working with your code and now we have two Kinects running simultaneously to account for the occlusion of our scene. We were wondering if there was some code readily available that you may have worked on in the past to run two Kinects on one system using the SingleHandTracking.py code. 

Very Respectfully,
Innovative Freshman Group RIT
1-716-421-4181
dpc9190@rit.edu

**Comment by padeler** [comment]
Hello,

The hand tracker expects input from just one camera, any modifications that would add a second one would require changes to the objective as well. Unfortunately this is not possible with the current version. 

You could create a synthetic view (synthetic depth map) from the 2 kinect inputs which would minimize the occlusions and use it to track the hand, but it is a suboptimal solution and I doubt it would give any significant performance gains.
