### ISSUE TITLE
No module names PyMBVCore

### ISSUE THREAD

**Issue by iamlegolas** [FORTH-ModelBasedTracker/HandTracker#41]
I'm using the Kinect VERSION 1 on Windows 7. I followed all the steps. In the end when I execute the batch file, I get the error that's attached. Any assistance is welcomed. 

Thankyou
![issue](https://cloud.githubusercontent.com/assets/16097130/15963186/7c14c348-2f29-11e6-9087-6c7e0e339f8a.png)

**Comment by padeler** [comment]
Hello,

The MBV libs will not work on windows7, since they are linked against the Kinect2 libraries which are only available on windows8+.

**Comment by jin-qin** [comment]
![image](https://cloud.githubusercontent.com/assets/6630789/16258475/00040960-3813-11e6-98d7-9dcffe785a36.png)

The same error, ran on ubuntu 16.04, using softkinetic ds325

**Comment by padeler** [comment]
I have not tested the tracker on ubuntu 16.04 yet, but from the error message it looks like an issue with the version of opencv.

Can you run an ldd on libCore.so (after setting the LD_LIBRARY_PATH properly) to see what is missing?

**Comment by jin-qin** [comment]
where is libCore.so?

**Comment by padeler** [comment]
FORTH/HANDTRACKER/libs/libCore.so

**Comment by jin-qin** [comment]
![image](https://cloud.githubusercontent.com/assets/6630789/16259015/61d7e970-3815-11e6-9600-a21e0adc549a.png)

**Comment by padeler** [comment]
As i said in my previous reply, set the LD_LIBRARY_PATH first (before running ldd), to check the current folder i.e.: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.

This will fix the "not found" for libraries that are packaged with the tracker like boost and openmesh.

Also please send the whole output of ldd.

**Comment by jin-qin** [comment]
OK, I will try it, thx a lot.

**Comment by ashokbugude** [comment]
Same issue here . Below is my terminal screen output for ubuntu 16.04

zayyon@zayyon-MS-7693:~/zayyon/HandTracker-master$ ./runme.sh
MBV_LIBS Environment variable should point to the MBV libraries folder.
MBV_LIBS
Setting LD_LIBRARY_PATH and PYTHONPATH
Running the Single Hand Tracker script...
Traceback (most recent call last):
  File "src/SingleHandTracking.py", line 8, in <module>
    import PyMBVCore as Core
ImportError: No module named PyMBVCore

**Comment by padeler** [comment]
You need to set the MBV_LIBS variable to point to the mbv libraries folder as the script explains.

**Comment by ashokbugude** [comment]
I have set it, but getting  errors as shown below

zayyon@zayyon-MS-7693:~/zayyon/HandTracker-master$ export MBV_LIBS=/home/zayyon/zayyon/MBV_PythonAPI_Linux_1.1
zayyon@zayyon-MS-7693:~/zayyon/HandTracker-master$ ./runme.shMBV_LIBS Environment variable should point to the MBV libraries folder.
MBV_LIBS /home/zayyon/zayyon/MBV_PythonAPI_Linux_1.1
Setting LD_LIBRARY_PATH and PYTHONPATH
Running the Single Hand Tracker script...
Traceback (most recent call last):
  File "src/SingleHandTracking.py", line 8, in <module>
    import PyMBVCore as Core
ImportError: /home/zayyon/zayyon/MBV_PythonAPI_Linux_1.1/libs/libCore.so: undefined symbol: _ZN2cv9ExceptionC1EiRKSsS2_S2_i

**Comment by ashokbugude** [comment]
Below is the complete output of ldd libCore.so after running export LD_LIBRARY_PATH=$LD_LIBRARY_PATH

```
linux-vdso.so.1 =>  (0x00007ffc72b28000)
libOpenMeshCore.so.3.1 (0x00007f8cfffd6000)
libcudart.so.7.5 (0x00007f8cffd76000)
libboost_system.so.1.57.0 (0x00007f8cffb6e000)
libboost_filesystem.so.1.57.0 (0x00007f8cff956000)
libboost_thread.so.1.57.0 (0x00007f8cff736000)
libboost_serialization.so.1.57.0 (0x00007f8cff4d6000)
libboost_program_options.so.1.57.0 (0x00007f8cff266000)
libboost_log.so.1.57.0 (0x00007f8cfef96000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8cfed4e000)
libtbb.so.2 => /usr/lib/x86_64-linux-gnu/libtbb.so.2 (0x00007f8cfeb0e000)
libopencv_core.so.2.4 => /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4 (0x00007f8cfe6de000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8cfe356000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8cfe046000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8cfde2e000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8cfda5e000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8cfd856000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8cfd64e000)
/lib64/ld-linux-x86-64.so.2 (0x000055e557104000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8cfd42e000)
libGL.so.1 => /usr/lib/nvidia-361/libGL.so.1 (0x00007f8cfd19e000)
libGLX.so.0 => /usr/lib/nvidia-361/libGLX.so.0 (0x00007f8cfcf66000)
libGLdispatch.so.0 => /usr/lib/nvidia-361/libGLdispatch.so.0 (0x00007f8cfcc7e000)
libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f8cfc93e000)
libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f8cfc726000)
libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f8cfc4fe000)
libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f8cfc2f6000)
libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f8cfc0ee000)
```

**Comment by DirkBroenink** [comment]
I have this same issue on windows 10, with a fresh windows 10 install. I'm guessing I need to install something, but I don't know what it should be. I followed the steps mentioned.

> D:\Users\user\InsignityAR\FORTH\app>runme.bat
MBV_LIBS Environment variable should point to the MBV libraries folder.
MBV_LIBS
Setting PATH and PYTHONPATH
"Running the Single Hand Tracker script..."
Traceback (most recent call last):
  File "src\SingleHandTracking.py", line 8, in <module>
    import PyMBVCore as Core
ImportError: No module named PyMBVCore
(C:\Users\user\Anaconda2) D:\Users\user\InsignityAR\FORTH\app>

**Comment by Depth3D** [comment]
the library is not frrendly....
