### ISSUE TITLE
Use code with dataset.

### ISSUE THREAD

**Issue by naimaotberd** [FORTH-ModelBasedTracker/HandTracker#42]
Hi,
I want to use your code SingleHandTracking.py as a baseline to compare with other codes, but I'm wondering if it's possible to use your code with a recorded dataset.
Thanks

**Comment by padeler** [comment]
Hello,

You can record an ONI file using the NiViewer or similar software and the supply that on the grabber in the python [script](https://github.com/FORTH-ModelBasedTracker/HandTracker/blob/master/src/SingleHandTracking.py#L90) .

Make sure the oni file is recorded on VGA resolution for both depth and RGB, and that the depth stream is registered on the rgb.

**Comment by naimaotberd** [comment]
Ok thanks a lot for the useful reply.
Best regards.

2016-06-27 19:29 GMT+00:00 Panteleris Paschalis notifications@github.com:
