### ISSUE TITLE
Python to Matlab

### ISSUE THREAD

**Issue by ma581** [FORTH-ModelBasedTracker/HandTracker#44]
Hi FORTH :)

I am now trying to feed the coordinates of the model hand calculated during hand tracking into MATLAB (Windows 10). I am using Matlab to execute operating system command using the function `<system()>`. 

The error I get seems to be related to the hand tracking libraries. Kindly could you help me out? Thanks!

Error message in MATLAB

```
Setting PATH and PYTHONPATH 
"Running the Single Hand Tracker script..." 
Creating Renderer... 
Traceback (most recent call last): 
  File "C:\Users\store\Code\07_CBAS\HandTracker\src\SingleHandTracking.py", line 60, in <module> 
    ht = HT.HandTrackerLib(2048, 2048, 64, 64, erenderer) 
RuntimeError: E:\mbv\Decoding\GenericDecoder\GenericDecoder.cpp(1320): Throw in function void __cdecl MBV::Decoding::GenericDecoder::loadFromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool) 
Dynamic exception type: struct MBV::Core::Exception 
[struct MBV::Core::Message * __ptr64] = could not open file for reading 
[struct MBV::Core::OffendingCode * __ptr64] = ifs.good()
```

**Comment by padeler** [comment]
It looks like the working directory for your script is not setup properly. It should be the same as the directory where the ".bat" file is.

**Comment by ma581** [comment]
Thanks that did the trick! :D

**Comment by ehewage** [comment]
My goal with combining the hand tracker is to be able to control a robotic hand that is controlled through Matlab. 

I am able to run SingleHandTracking.py from Matlab but I am not sure about the best way to enable Matlab to access the hand tracking variables that are updated in SingleHandTracking.py in real-time. 

At present, in Matlab, I am using:  
```[status, result] = system('C:\Users\store\Code\07_CBAS\HandTracker\runme2.bat')```
And in SingleHandTracking.pyI have added a line: 
```print("Matrix = ", matrix)``` which has decoded model hand coordinates. 
However, Matlab is not able to access the variable (called *matrix* ) live (but only after I have stopped the hand tracker).  

Is there a suitable method to enable live update of the variable within Matlab? 
Is there a method to pipe the Python variable to Matlab in Windows? 

Thanks!!

**Comment by ma581** [comment]
My goal with combining the hand tracker is to be able to control a robotic hand that is controlled through Matlab. 

I am able to run SingleHandTracking.py from Matlab but I am not sure about the best way to enable Matlab to access the hand tracking variables that are updated in SingleHandTracking.py in real-time. 

#### Attempted method 1 (Directly calling from Matlab)

At present, in Matlab, I am using:  

``` matlab
[status, result] = system('C:\Users\store\Code\07_CBAS\HandTracker\runme2.bat')
```

And in SingleHandTracking.pyI have added a line: 

``` python
print("Matrix = ", matrix) #decoded model hand coordinates. 
```

However, Matlab is not able to access the variable (called _matrix_ ) live (but only after I have stopped the hand tracker).  

Is there a method of fixing this attempt?

#### Attempted method 2 (UDP port)

Adding UDP port communication to SingleHandTracking.py

``` python
import socket
import struct 
UDP_IP = "127.0.0.1"
UDP_PORT = 5005
sock = socket.socket(socket.AF_INET, # Internet
                    socket.SOCK_DGRAM) # UDP
...
while True:
     ...
    message = str(matrix[:,[0,1,2]]) #Matrix is a numpy array with 3D homogeneous coordinates
    sock.sendto(struct.pack('I', len(message )) + message , (UDP_IP, UDP_PORT)) 
```

This sends the data in ASCII format and reading this from Matlab is messy. Is there a way to pre process/ post process UDP port communication better? Is there a method to pipe the Python variable to Matlab in Windows? 

Thanks!!

**Comment by nkyriazis** [comment]
InterProcess Communication seems indeed the suitable route. You can try sending the data in binary form (27 doubles) and reading it back in matlab in binary form too, so no parsing is needed.
