### ISSUE TITLE
Add a demo that uses a live OpenNI source

### ISSUE THREAD

**Issue by severin-lemaignan** [FORTH-ModelBasedTracker/HandTracker#5]
The provided demo ([SingleHandTracking.py](https://github.com/FORTH-ModelBasedTracker/HandTracker/blob/master/src/SingleHandTracking.py)) takes a reference ONI file as input. It would be nice to have an example that shows how to use a live RGBD stream as well (or at least some documentation for the API of `Acquisition.OpenNIGrabber`)

**Comment by nkyriazis** [comment]
Please have a look at this [comment](https://github.com/FORTH-ModelBasedTracker/HandTracker/blob/master/src/SingleHandTracking.py#L89). You'll find that it suffices to set <tt>oniPath</tt> ([next line](https://github.com/FORTH-ModelBasedTracker/HandTracker/blob/master/src/SingleHandTracking.py#L90)) to the empty string.
