### ISSUE TITLE
Get 3D position of the fingertips

### ISSUE THREAD

**Issue by rarocena** [FORTH-ModelBasedTracker/HandTracker#53]
Hi, we recently started doing some tests with your library and the SingleHandTracking. We are part of an academic project at the School of Engineering, Universidad de la República, Uruguay in which we are studying certain attributes of the hand that influence the intention of the gesture. For that purpose it would be useful to have the 3D position of the fingertips.

From what we understand, you use a sphere to draw the the fingertips. It would be very helpful for us if we could obtain the 3D position of the center of the sphere. Is it possible ? We would appreciate any help you could provide us.

Thanks.

**Comment by padeler** [comment]
Hello, you can see the answer to issue #16 for an answer to your question.

**Comment by rarocena** [comment]
Hi, thanks for the response. 
We did some tests with the SingleHandTracking.py script with the changes that nkyriazis mentioned in the issue #16, and we saw that after decoding the currentHandPose whith the line "decoding = ht.decoder.quickDecode(currentHandPose)" the decoding.values hast two elements. One with 22 points and another with 15 points. Could you tell us, the correspondence between that 37 points and the joints  of the hand? Specially those which represent the fingertips.

Thanks.

**Comment by rarocena** [comment]
Hi, thanks for the response.
We did some tests with the SingleHandTracking.py script with the changes that nkyriazis mentioned in the issue #16, and we saw that after decoding the currentHandPose whith the line "decoding = ht.decoder.quickDecode(currentHandPose)" the decoding.values hast two elements. One with 22 points and another with 15 points. Could you tell us, the correspondence between that 37 points and the joints of the hand? Specially those which represent the fingertips.

Thanks.

**Comment by oikonom** [comment]
Hello,

These 37 elements are actually homogeneous transformation matrices, transforming 15 cylinders and 22 spheres to build the hand model. Out of these, the fingertips are 5 spheres. Use this snip to extract the centres of these spheres:


decoding = ht.decoder.quickDecode(currentHandPose) # same line as before
decodedSpheres = decoding.values()[0] # get the spheres
fingertipCenters = [decodedSpheres.matrices[i].data[3,0:3] for i in [8, 17, 21, 13, 4]] # indices of fingertips

The indexed finger order is from thumb to pinky.

Depending on what you want to do with this information, you may also need the orientation of the fingertip (more precisely, the last phalanx). This information can be again extracted with this snip, in the form of 3x3 rotation matrices. To do this, just change the .data[3,0:3] to .data[0:3,0:3] to get the top-left 3x3 part of the matrix. Note that you may need to transpose the result: we follow the usual convention in graphics (right-multiplication) which is transposed compared to the usual linear algebra representation of homogeneous transformations.
