### ISSUE TITLE
tracking FPS and ui FPS  just 1 and  runs without tracking(kinect v2)

### ISSUE THREAD

**Issue by PengfeiRen96** [FORTH-ModelBasedTracker/HandTracker#56]
i have placed your hand over the super-imposed hand model shown on the "Hand Tracker" window and pressed 's'. but the hand is not being tracked. 
Tracking FPS and ui FPS  just 1(GPU: GeForce GT 750M)

**Comment by padeler** [comment]
Can you provide a bit more information on that (OS, CPU, Camera)? The GT750M is not a very fast gpu and will run the tracker rather slowly especially if you have a slow cpu.
