### ISSUE TITLE
Output Syntax Error

### ISSUE THREAD

**Issue by mecastro** [FORTH-ModelBasedTracker/HandTracker#58]
I've made a progress and the numpy is now importing perfectly but i encountered another problem

![screennshot 2](https://cloud.githubusercontent.com/assets/13103959/24489657/54197fa0-1551-11e7-9c27-14694d7fcfb4.png)

Pls help

**Comment by mecastro** [comment]
this is a much better screenshot 

![screenshot_6](https://cloud.githubusercontent.com/assets/13103959/24494256/7bd416a6-14e6-11e7-9002-d6e7cfcef4cf.png)

**Comment by padeler** [comment]
You probably have two graphics cards on your laptop. You must disable the intel one kai keep only the nvidia card enabled. Check issue #23 for more details.

**Comment by mecastro** [comment]
@padeler i only have  1 graphics, although its only the onboard graphic cards, is that ok 

![screenshot_6](https://cloud.githubusercontent.com/assets/13103959/24495122/0aa5bb44-14e9-11e7-9a30-03317b2b8d8a.png)

**Comment by padeler** [comment]
You need an NVidia GPU to run the tracker.
