### ISSUE TITLE
Im only using one graphics card

### ISSUE THREAD

**Issue by mecastro** [FORTH-ModelBasedTracker/HandTracker#59]
@padeler i only have  1 graphics card, although its only the onboard graphic cards, is that ok 

![screenshot_6](https://cloud.githubusercontent.com/assets/13103959/24495122/0aa5bb44-14e9-11e7-9a30-03317b2b8d8a.png)

**Comment by padeler** [comment]
The Hand tracker required an NVidia GPU with CUDA support (compute capability >=3.0). It will not work on an intel gpu.
