### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by mecastro** [FORTH-ModelBasedTracker/HandTracker#60]
ok i have an nvidia now and i encountered a new error here is the screencap 

![screenshot_6](https://cloud.githubusercontent.com/assets/13103959/24576274/cd350662-166d-11e7-99ed-aec75baba97d.png)

hope you can help me thank you

**Comment by mecastro** [comment]
NVM already fixed the issue 

one last issue tho how to speed up the tracking

**Comment by padeler** [comment]
The tracker's performance is bounded by your GPU and to a (much) lesser degree by your CPU. You should be able to get 25+ fps using a NVidia GTX 580 or better on an modern i3 CPU.

**Comment by asd2846531** [comment]
Hi,
I have the same Index out of range issue.
Can you provide your solution to the issue?

Many thanks

**Comment by padeler** [comment]
Hello, the actual error is higher up: The OpenNI cannot read the recording file. Try using a different oni recording or just open directly the camera. Check the comments in the python file for more information.
