### ISSUE TITLE
Python Version Problem

### ISSUE THREAD

**Issue by rongjincs** [FORTH-ModelBasedTracker/HandTracker#64]
My machine is windows 10. 
I am using Python 2.7.13 |Anaconda custom (64-bit)|, numpy version is '1.13.1', but I still met the following issue: 
>>> import cv2
ImportError: numpy.core.multiarray failed to import

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import

Anyone has solutions??? Can I update Python 2.7.13 to 3.4+??

**Comment by padeler** [comment]
Make sure pyopencv is properly installed on your systesm.

This is a anaconda/opencv related issue and not related to the HandTracker.  Closing.
