### ISSUE TITLE
Module PyMBVCore not found (Win10)

### ISSUE THREAD

**Issue by iDaN5x** [FORTH-ModelBasedTracker/HandTracker#66]
Hello,

I'm trying to run the HandTracker demo application provided here, with no success.
I have installed all the required dependencies, and set the MBV_LIBS variables as required.
However, when running the `runme.bat` file, python throws out an ImportError for PyMBVCore...

![capture2](https://user-images.githubusercontent.com/3427523/28634524-2025a858-7240-11e7-9a4c-20cb69f8335d.PNG)

Can you help me solve this problem?

Thanks.

**Comment by iDaN5x** [comment]
@padeler

_Sent from my Samsung SM-G955F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by padeler** [comment]
Hello,

PyMBVCore is located inside the python_libs folder. From your screenshot it looks like you have set the environment MBV_LIBS variable to point to the correct folder. 

Maybe you have a missing dependency?

**Comment by rongjincs** [comment]
I have the same problem on Win8 and the following versions:
numpy1.13.1
scipy0.16.1
matplotlib2.0.2
opencv2.4.13.2

**Comment by lyyiangang** [comment]
I meet the same problem. It says "DLL load failed"  but I can't get more details about this failure. I don't know what exact DLL is missed. 
Note: I am using the graphical card of AMD instead of NVIDIA.  Is it the root cause of this import error??
Could you please give any tips?
Thanks very much.

**Comment by padeler** [comment]
The handtracker will only work with NVIDIA GPUs. CUDA is a hard dependency.

**Comment by rongjincs** [comment]
C:\FORTH\HandTracker>runme.bat
MBV_LIBS Environment variable should point to the MBV libraries fol
MBV_LIBS C:\FORTH\HandTracker
Setting PATH and PYTHONPATH
"Running the Single Hand Tracker script..."
Traceback (most recent call last):
  File "src\SingleHandTracking.py", line 8, in <module>
    import PyMBVCore as Core
ImportError: DLL load failed: %1 is not a valid Win32 application.

what is this problem?

**Comment by rongjincs** [comment]
copy C:\opencv\build\python\2.7\x64\cv2.pyd into python site-package folder...
