### ISSUE TITLE
GLSL 3.30 is not supported

### ISSUE THREAD

**Issue by solmn** [FORTH-ModelBasedTracker/HandTracker#70]
[2017-08-05 17:38:17.684438] [0x000007fd3c18a274] [warning] Read options from environment : unrecognised option 'libs'
[2017-08-05 17:38:17.684528] [0x000007fd3c18a274] [warning] Read options from environment : unrecognised option 'libs'
Traceback (most recent call last):
  File "src/HandObjectTracking.py", line 33, in <module>
    renderer = Rendering.RendererOGLCudaExposed.get()
RuntimeError: /home/padeler/work/mbv/release_libs/src/mbv/Rendering/RendererOGL/OpenGLHelpers.cpp(158): Throw in function void OGL::ThrowOnCompileLinkError(GLuint, OGL::CompLinkMode, const String&)
Dynamic exception type: boost::exception_detail::clone_impl<MBV::Core::Exception>
[MBV::Core::Message*] = error while compiling file :
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Can you help me with this error please??

I am installing it in Ubuntu Linux 14.04   64bit computer. and I get errors as shown below

s@s:~$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Desktop 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.1.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:

**Comment by padeler** [comment]
What GPU and driver version do you have?
