### ISSUE TITLE
unrecognise option 'libs'

### ISSUE THREAD

**Issue by kheito** [FORTH-ModelBasedTracker/HandTracker#71]
I connected the 3d hand tracking to labview. It is running and successfully transmit data to labview but the problem is it just suddenly quitting itself after probably few minutes after running it. This is a screenshot of what I am getting when I'm running it. Hope you'll help, thanks in advance
![unrecognise option libs](https://user-images.githubusercontent.com/26784621/29237285-c6ff32ec-7f4d-11e7-8f10-72a45583c259.jpg)

**Comment by padeler** [comment]
Hello,

The warning about the libs environment variable is unrelated to your issues. Can you increase the [log level](https://github.com/FORTH-ModelBasedTracker/HandTracker/blob/master/src/SingleHandTracking.py#L30) to "debug"  and post the log output before the crash? 
Maybe this will give us a clue on whats going on.

**Comment by kheito** [comment]
Sorry for the late reply, quick question. How and where can I increase the log severity? 

Thanks

**Comment by padeler** [comment]
In the hand tracker script [here](https://github.com/FORTH-ModelBasedTracker/HandTracker/blob/master/src/SingleHandTracking.py#L30) change "error" to "debug"
