### ISSUE TITLE
can I use this lib to track two hands ?

### ISSUE THREAD

**Issue by sophiatse** [FORTH-ModelBasedTracker/HandTracker#84]
Sir,
I'm wondering if this lib can be used to track two separate hands?
thanks advanced!

**Comment by padeler** [comment]
You could use the library to track two separate hands if you provide a left hand model. The results, however, wont be optimal since the hand interactions (occlusions) wont be taken into account in the objective function.  Our two-hands aware objective function is not part of this release.
